server:
  port: 8007
spring:
  rabbitmq:
    host: 192.168.2.129
    port: 5672
    username: root
    password: 123456
  redis:
    host: 192.168.2.129
    port: 6379
    database: 0
    timeout: 1800000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.129:8848